# Generated by Django 4.2a1 on 2023-03-07 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "winner_team",
                    models.CharField(
                        blank=True,
                        choices=[("team_a", "Team A"), ("team_b", "Team B")],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "Loading"), (1, "Running"), (2, "Finished")],
                        default=0,
                        null=True,
                    ),
                ),
                ("team_a_score", models.IntegerField(blank=True, default=0, null=True)),
                ("team_b_score", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "game_type",
                    models.CharField(
                        choices=[("custom", "Custom"), ("competitive", "Competitive")],
                        max_length=16,
                    ),
                ),
                (
                    "game_mode",
                    models.IntegerField(
                        choices=[(1, "Solo"), (5, "Defuse"), (20, "Dm")]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchPlayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team",
                    models.CharField(
                        choices=[("team_a", "Team A"), ("team_b", "Team B")],
                        max_length=16,
                    ),
                ),
                ("kills", models.IntegerField(blank=True, default=0, null=True)),
                ("deaths", models.IntegerField(blank=True, default=0, null=True)),
                ("assists", models.IntegerField(blank=True, default=0, null=True)),
                ("damage", models.IntegerField(blank=True, default=0, null=True)),
                ("hs_kills", models.IntegerField(blank=True, default=0, null=True)),
                ("afk", models.IntegerField(blank=True, default=0, null=True)),
                ("plants", models.IntegerField(blank=True, default=0, null=True)),
                ("defuses", models.IntegerField(blank=True, default=0, null=True)),
                ("double_kills", models.IntegerField(blank=True, default=0, null=True)),
                ("triple_kills", models.IntegerField(blank=True, default=0, null=True)),
                ("quadra_kills", models.IntegerField(blank=True, default=0, null=True)),
                ("aces", models.IntegerField(blank=True, default=0, null=True)),
                ("clutch_v1", models.IntegerField(blank=True, default=0, null=True)),
                ("clutch_v2", models.IntegerField(blank=True, default=0, null=True)),
                ("clutch_v3", models.IntegerField(blank=True, default=0, null=True)),
                ("clutch_v4", models.IntegerField(blank=True, default=0, null=True)),
                ("clutch_v5", models.IntegerField(blank=True, default=0, null=True)),
                ("firstkills", models.IntegerField(blank=True, default=0, null=True)),
                ("shots_fired", models.IntegerField(blank=True, default=0, null=True)),
                ("head_shots", models.IntegerField(blank=True, default=0, null=True)),
                ("chest_shots", models.IntegerField(blank=True, default=0, null=True)),
                ("leg_shots", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="matches.match"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
