# Generated by Django 4.2 on 2023-05-26 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Loading"),
                            (1, "Ready"),
                            (2, "Running"),
                            (3, "Finished"),
                            (4, "Cancelled"),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
                (
                    "game_type",
                    models.CharField(
                        choices=[("custom", "Custom"), ("competitive", "Competitive")],
                        max_length=16,
                    ),
                ),
                (
                    "game_mode",
                    models.IntegerField(
                        choices=[(1, "Solo"), (5, "Defuse"), (20, "Dm")]
                    ),
                ),
            ],
            options={
                "ordering": ["-end_date"],
            },
        ),
        migrations.CreateModel(
            name="MatchPlayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(editable=False)),
                ("level_points", models.IntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
                ("name", models.CharField(max_length=32)),
                ("key", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MatchTeam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("score", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="matches.match"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchPlayerStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kills", models.IntegerField(blank=True, default=0, null=True)),
                ("deaths", models.IntegerField(blank=True, default=0, null=True)),
                ("assists", models.IntegerField(blank=True, default=0, null=True)),
                ("damage", models.IntegerField(blank=True, default=0, null=True)),
                ("hs_kills", models.IntegerField(blank=True, default=0, null=True)),
                ("afk", models.IntegerField(blank=True, default=0, null=True)),
                ("plants", models.IntegerField(blank=True, default=0, null=True)),
                ("defuses", models.IntegerField(blank=True, default=0, null=True)),
                ("double_kills", models.IntegerField(blank=True, default=0, null=True)),
                ("triple_kills", models.IntegerField(blank=True, default=0, null=True)),
                ("quadra_kills", models.IntegerField(blank=True, default=0, null=True)),
                ("aces", models.IntegerField(blank=True, default=0, null=True)),
                ("clutch_v1", models.IntegerField(blank=True, default=0, null=True)),
                ("clutch_v2", models.IntegerField(blank=True, default=0, null=True)),
                ("clutch_v3", models.IntegerField(blank=True, default=0, null=True)),
                ("clutch_v4", models.IntegerField(blank=True, default=0, null=True)),
                ("clutch_v5", models.IntegerField(blank=True, default=0, null=True)),
                ("firstkills", models.IntegerField(blank=True, default=0, null=True)),
                ("shots_fired", models.IntegerField(blank=True, default=0, null=True)),
                ("head_shots", models.IntegerField(blank=True, default=0, null=True)),
                ("chest_shots", models.IntegerField(blank=True, default=0, null=True)),
                ("other_shots", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="matches.matchplayer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="matchplayer",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="matches.matchteam"
            ),
        ),
        migrations.AddField(
            model_name="matchplayer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="matches.server"
            ),
        ),
    ]
