# Generated by Django 4.2rc1 on 2023-03-25 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
                ("name", models.CharField(max_length=32)),
                ("key", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="server",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="matches.server",
            ),
            preserve_default=False,
        ),
    ]
