# Generated by Django 4.2rc1 on 2023-03-25 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matches", "0002_server_match_server"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="team_a_score",
        ),
        migrations.RemoveField(
            model_name="match",
            name="team_b_score",
        ),
        migrations.RemoveField(
            model_name="match",
            name="winner_team",
        ),
        migrations.AlterField(
            model_name="matchplayer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="MatchTeam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("score", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="matches.match"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="matchplayer",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="matches.matchteam"
            ),
        ),
    ]
