# Generated by Django 4.2 on 2023-07-01 05:06

from django.db import migrations


def create_default_map(apps, schema_editor):
    Map = apps.get_model("matches", "Map")
    Map.objects.create(id=1, name='Auditório', sys_name='auditorium')


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0002_map"),
    ]

    operations = [
        migrations.RunPython(create_default_map),
    ]
