# Generated by Django 4.2rc1 on 2023-03-25 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "matches",
            "0003_remove_match_team_a_score_remove_match_team_b_score_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchplayer",
            name="match",
        ),
    ]
