# Generated by Django 4.2 on 2023-07-01 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0003_auto_20230701_0206"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="map",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="matches.map"
            ),
        ),
    ]
