# Generated by Django 4.2 on 2023-07-14 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0004_match_map"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="server",
            name="key",
        ),
    ]
