# Generated by Django 4.2rc1 on 2023-03-25 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0004_remove_matchplayer_match"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matchplayer",
            old_name="leg_shots",
            new_name="other_shots",
        ),
    ]
