# Generated by Django 4.2rc1 on 2023-03-26 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matches", "0005_rename_leg_shots_matchplayer_other_shots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchplayer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
