# Generated by Django 4.2rc1 on 2023-04-08 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0007_alter_match_server"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchplayer",
            name="aces",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="afk",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="assists",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="chest_shots",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="clutch_v1",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="clutch_v2",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="clutch_v3",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="clutch_v4",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="clutch_v5",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="damage",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="deaths",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="defuses",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="double_kills",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="firstkills",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="head_shots",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="hs_kills",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="kills",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="other_shots",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="plants",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="quadra_kills",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="shots_fired",
        ),
        migrations.RemoveField(
            model_name="matchplayer",
            name="triple_kills",
        ),
        migrations.CreateModel(
            name="MatchPlayerStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kills", models.IntegerField(blank=True, default=0, null=True)),
                ("deaths", models.IntegerField(blank=True, default=0, null=True)),
                ("assists", models.IntegerField(blank=True, default=0, null=True)),
                ("damage", models.IntegerField(blank=True, default=0, null=True)),
                ("hs_kills", models.IntegerField(blank=True, default=0, null=True)),
                ("afk", models.IntegerField(blank=True, default=0, null=True)),
                ("plants", models.IntegerField(blank=True, default=0, null=True)),
                ("defuses", models.IntegerField(blank=True, default=0, null=True)),
                ("double_kills", models.IntegerField(blank=True, default=0, null=True)),
                ("triple_kills", models.IntegerField(blank=True, default=0, null=True)),
                ("quadra_kills", models.IntegerField(blank=True, default=0, null=True)),
                ("aces", models.IntegerField(blank=True, default=0, null=True)),
                ("clutch_v1", models.IntegerField(blank=True, default=0, null=True)),
                ("clutch_v2", models.IntegerField(blank=True, default=0, null=True)),
                ("clutch_v3", models.IntegerField(blank=True, default=0, null=True)),
                ("clutch_v4", models.IntegerField(blank=True, default=0, null=True)),
                ("clutch_v5", models.IntegerField(blank=True, default=0, null=True)),
                ("firstkills", models.IntegerField(blank=True, default=0, null=True)),
                ("shots_fired", models.IntegerField(blank=True, default=0, null=True)),
                ("head_shots", models.IntegerField(blank=True, default=0, null=True)),
                ("chest_shots", models.IntegerField(blank=True, default=0, null=True)),
                ("other_shots", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matches.matchplayer",
                    ),
                ),
            ],
        ),
    ]
