# Generated by Django 4.2rc1 on 2023-04-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0009_alter_matchplayerstats_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchplayerstats",
            name="player",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="matches.matchplayer",
            ),
        ),
    ]
