# Generated by Django 4.2 on 2023-09-08 21:23

from django.db import migrations, models
import matches.models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0010_server_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to=matches.models.map_media_path),
        ),
        migrations.AlterField(
            model_name="map",
            name="sys_name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
