# Generated by Django 4.2 on 2023-04-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0010_alter_matchplayerstats_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Loading"), (1, "Ready"), (2, "Running"), (3, "Finished")],
                default=0,
                null=True,
            ),
        ),
    ]
