# Generated by Django 4.2 on 2023-09-22 20:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0011_map_thumbnail_alter_map_sys_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"ordering": ["-end_date"], "verbose_name_plural": "matches"},
        ),
    ]
