# Generated by Django 4.2 on 2023-09-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0011_map_thumbnail_alter_map_sys_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="api_port",
            field=models.IntegerField(default=3000),
        ),
    ]
