# Generated by Django 4.2 on 2023-04-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0012_alter_match_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchplayer",
            name="level",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="matchplayer",
            name="level_points",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
