# Generated by Django 4.2 on 2023-09-25 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0012_alter_match_options"),
        ("matches", "0012_server_api_port"),
    ]

    operations = []
