# Generated by Django 4.2 on 2023-04-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0013_matchplayer_level_matchplayer_level_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchplayer",
            name="level",
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="matchplayer",
            name="level_points",
            field=models.IntegerField(editable=False),
        ),
    ]
