# Generated by Django 4.2 on 2023-10-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0013_merge_0012_alter_match_options_0012_server_api_port"),
    ]

    operations = [
        migrations.CreateModel(
            name="BetaUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("steamid_hex", models.CharField(max_length=64)),
                ("username", models.CharField(max_length=32)),
                ("date_add", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
