# Generated by Django 4.2 on 2023-10-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0014_betauser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="betauser",
            options={"ordering": ["-date_add"], "verbose_name_plural": "beta users"},
        ),
        migrations.AddField(
            model_name="betauser",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="betauser",
            index=models.Index(fields=["email"], name="matches_bet_email_7aff6a_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["status"], name="matches_mat_status_a896a5_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["end_date"], name="matches_mat_end_dat_b01d3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["start_date"], name="matches_mat_start_d_6a4cce_idx"
            ),
        ),
    ]
