# Generated by Django 4.2 on 2023-05-06 04:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0001_squashed_0014_alter_matchplayer_level_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"ordering": ["-end_date"]},
        ),
    ]
