# Generated by Django 4.2 on 2023-10-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0015_alter_betauser_options_betauser_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betauser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
