# Generated by Django 4.2 on 2023-10-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0016_alter_betauser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betauser",
            name="steamid_hex",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
