# Generated by Django 4.2 on 2023-11-06 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0018_alter_server_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="matches.map"
            ),
        ),
    ]
