# Generated by Django 4.2 on 2024-01-31 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0019_alter_match_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="weight",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
