# Generated by Django 4.2 on 2024-01-31 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0020_map_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="weight",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
