# Generated by Django 4.2 on 2024-02-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0021_alter_map_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="game_type",
        ),
        migrations.AlterField(
            model_name="match",
            name="game_mode",
            field=models.CharField(
                choices=[
                    ("competitive", "Competitive"),
                    ("custom", "Custom"),
                    ("tdm", "Tdm"),
                ],
                max_length=32,
            ),
        ),
    ]
