# Generated by Django 4.2 on 2024-02-21 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matches", "0022_remove_match_game_type_match_match_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="restricted_weapon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weapon_appistol", "Weapon Appistol"),
                    ("weapon_assaultrifle", "Weapon Assaultrifle"),
                    ("weapon_assaultshotgun", "Weapon Assaultshotgun"),
                    ("weapon_combatmg", "Weapon Combatmg"),
                    ("weapon_heavysniper", "Weapon Heavysniper"),
                    ("weapon_mg", "Weapon Mg"),
                    ("weapon_microsmg", "Weapon Microsmg"),
                    ("weapon_pistol", "Weapon Pistol"),
                    ("weapon_pistol50", "Weapon Pistol50"),
                    ("weapon_pistol_mk2", "Weapon Pistol Mk2"),
                    ("weapon_pumpshotgun", "Weapon Pumpshotgun"),
                    ("weapon_smg", "Weapon Smg"),
                    ("weapon_sniperrifle", "Weapon Sniperrifle"),
                    ("weapon_tacticalrifle", "Weapon Tacticalrifle"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="MatchSpectator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="matches.match"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
