# Generated by Django 4.2 on 2024-02-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0023_match_restricted_weapon_matchspectator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="match_type",
        ),
        migrations.AddField(
            model_name="map",
            name="map_type",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("deathmatch", "Deathmatch"),
                    ("safezone", "Safezone"),
                ],
                default="default",
                max_length=32,
            ),
        ),
    ]
