# Generated by Django 4.2 on 2024-02-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0024_remove_match_match_type_map_map_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="map_type",
            field=models.CharField(
                choices=[("default", "Default"), ("safezone", "Safezone")],
                default="default",
                max_length=32,
            ),
        ),
    ]
