# Generated by Django 4.2 on 2024-03-04 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0025_alter_map_map_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchteam",
            name="side",
            field=models.IntegerField(choices=[(1, "Def"), (2, "Atk")], default=1),
        ),
        migrations.AlterField(
            model_name="matchplayer",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="matches.matchteam",
            ),
        ),
        migrations.DeleteModel(
            name="MatchSpectator",
        ),
    ]
