# Generated by Django 4.2 on 2024-03-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0026_matchteam_side_alter_matchplayer_team_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchteam",
            name="side",
            field=models.IntegerField(choices=[(1, "Def"), (2, "Atk")]),
        ),
    ]
