# Generated by Django 4.2 on 2024-03-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0028_matchplayer_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="server_type",
            field=models.CharField(
                choices=[("default", "Default"), ("safezone", "Safezone")],
                default="default",
                max_length=32,
            ),
        ),
    ]
