# Generated by Django 4.2 on 2024-03-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0029_server_server_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="sys_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="map",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
