# Generated by Django 4.2 on 2023-08-05 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("description", models.TextField()),
                ("discount", models.IntegerField(default=0)),
                (
                    "background_image",
                    models.ImageField(upload_to=store.models.item_media_path),
                ),
                (
                    "foreground_image",
                    models.FileField(upload_to=store.models.item_media_path),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("description", models.TextField()),
                ("discount", models.IntegerField(default=0)),
                (
                    "background_image",
                    models.ImageField(upload_to=store.models.item_media_path),
                ),
                (
                    "foreground_image",
                    models.FileField(upload_to=store.models.item_media_path),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("wear", "Wear"),
                            ("weapon", "Weapon"),
                            ("consumable", "Consumable"),
                            ("persona", "Persona"),
                            ("spray", "Spray"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        choices=[("def", "Def"), ("ata", "Ata")], max_length=32
                    ),
                ),
                ("handle", models.CharField(max_length=128, unique=True)),
                ("price", models.IntegerField()),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("release_date", models.DateTimeField(null=True)),
                ("is_available", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("discount", models.IntegerField(default=0)),
                (
                    "background_image",
                    models.ImageField(upload_to=store.models.item_media_path),
                ),
                (
                    "foreground_image",
                    models.FileField(upload_to=store.models.item_media_path),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                ("in_use", models.BooleanField(default=False)),
                ("open_date", models.DateTimeField(null=True)),
                (
                    "box",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.box",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.collection",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.item"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=store.models.item_media_path)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("video", "Video"), ("image", "Image")], max_length=16
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.item"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="owners",
            field=models.ManyToManyField(
                through="store.UserItem", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.collection",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.item",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="collection",
            name="items",
            field=models.ManyToManyField(
                through="store.CollectionItem", to="store.item"
            ),
        ),
        migrations.CreateModel(
            name="BoxItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("draw_chance", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.box"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.item",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="box",
            name="items",
            field=models.ManyToManyField(through="store.BoxItem", to="store.item"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["handle"], name="store_item_handle_178093_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["price"], name="store_item_price_feb942_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["is_available"], name="store_item_is_avai_49f740_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["release_date"], name="store_item_release_7a5e8a_idx"
            ),
        ),
    ]
