# Generated by Django 4.2 on 2023-11-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="producttransaction",
            name="store_produ_transac_bb1fda_idx",
        ),
        migrations.RemoveField(
            model_name="producttransaction",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="producttransaction",
            name="complete_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producttransaction",
            name="session_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="producttransaction",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("complete", "Complete")],
                default="open",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="producttransaction",
            name="price",
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name="producttransaction",
            name="product_id",
            field=models.CharField(max_length=256),
        ),
        migrations.AddIndex(
            model_name="producttransaction",
            index=models.Index(
                fields=["session_id"], name="store_produ_session_2edf9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="producttransaction",
            index=models.Index(fields=["status"], name="store_produ_status_e10b4b_idx"),
        ),
    ]
