# Generated by Django 4.2 on 2023-10-03 21:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userbox",
            unique_together={("user", "box")},
        ),
        migrations.AlterUniqueTogether(
            name="useritem",
            unique_together={("user", "item")},
        ),
    ]
