# Generated by Django 4.2 on 2023-08-05 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_item_subtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useritem",
            name="box",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.box",
            ),
        ),
        migrations.AlterField(
            model_name="useritem",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.collection",
            ),
        ),
    ]
