# Generated by Django 4.2 on 2023-11-08 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0003_userbox_store_userb_can_ope_e27fb8_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("name", models.CharField(max_length=64)),
                ("gateway_id", models.CharField(max_length=256, unique=True)),
                ("is_available", models.BooleanField(default=False)),
                ("is_sandbox", models.BooleanField(default=False)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                ("discount", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="box",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="collection",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name="ProductTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("gateway_id", models.CharField(max_length=256, unique=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "transactions",
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["gateway_id"], name="store_produ_gateway_7c752d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="producttransaction",
            index=models.Index(
                fields=["gateway_id"], name="store_produ_gateway_e5288c_idx"
            ),
        ),
    ]
