# Generated by Django 4.2 on 2024-01-03 19:40

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_alter_box_background_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=store.models.item_background_media_path
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=store.models.item_background_media_path
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=store.models.item_background_media_path
            ),
        ),
    ]
