# Generated by Django 4.2 on 2024-01-04 14:12

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_box_background_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="featured_image",
            field=models.FileField(
                default="None", upload_to=store.models.item_featured_media_path
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="featured_image",
            field=models.FileField(
                default="None", upload_to=store.models.item_featured_media_path
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="featured_image",
            field=models.FileField(
                default="None", upload_to=store.models.item_featured_media_path
            ),
        ),
    ]
