# Generated by Django 4.2 on 2024-01-05 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_box_featured_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userbox",
            options={"ordering": ["box__id"], "verbose_name_plural": "user boxes"},
        ),
        migrations.AlterModelOptions(
            name="useritem",
            options={"ordering": ["item__id"]},
        ),
    ]
