# Generated by Django 4.2 on 2024-01-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_alter_userbox_options_alter_useritem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_starter",
            field=models.BooleanField(default=False),
        ),
    ]
