# Generated by Django 4.2 on 2024-01-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_item_is_starter"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="weapon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pistola", "Pistola"),
                    ("Rapidinha", "Rapidinha"),
                    ("9idade", "Novidade"),
                    ("Trinta e Oito", "Trinta E Oito"),
                    ("Micro", "Micro"),
                    ("Nova", "Nova"),
                    ("Doze", "Doze"),
                    ("Bull", "Bull"),
                    ("Rambinho", "Rambinho"),
                    ("Rambão", "Rambao"),
                    ("AK", "Ak"),
                    ("M4", "M4"),
                    ("Teco-Teco", "Teco Teco"),
                    ("Sniper", "Sniper"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("def", "Def"),
                    ("ata", "Ata"),
                    ("card", "Card"),
                    ("profile", "Profile"),
                    ("pistol", "Pistol"),
                    ("smg", "Smg"),
                    ("shotgun", "Shotgun"),
                    ("machinegun", "Machinegun"),
                    ("rifles", "Rifles"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
