# Generated by Django 4.2 on 2024-01-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_item_weapon_alter_item_subtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("def", "Def"),
                    ("ata", "Ata"),
                    ("card", "Card"),
                    ("profile", "Profile"),
                    ("pistols", "Pistols"),
                    ("smgs", "Smgs"),
                    ("shotguns", "Shotguns"),
                    ("machineguns", "Machineguns"),
                    ("rifles", "Rifles"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
