# Generated by Django 4.2 on 2024-01-28 03:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0013_alter_box_cover_image_alter_collection_cover_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_rotation_date", models.DateTimeField()),
                ("next_rotation_date", models.DateTimeField()),
                (
                    "items_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=8
                    ),
                ),
                (
                    "last_rotation_items_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=8
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["next_rotation_date", "-last_rotation_date"],
            },
        ),
        migrations.AddIndex(
            model_name="userstore",
            index=models.Index(
                fields=["items_ids"], name="store_users_items_i_934c55_idx"
            ),
        ),
    ]
