# Generated by Django 4.2 on 2024-01-29 19:54

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0014_userstore_userstore_store_users_items_i_934c55_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="preview_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=store.models.item_preview_media_path
            ),
        ),
    ]
