# Generated by Django 4.2 on 2024-03-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0015_item_preview_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttransaction",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("card", "Card"), ("boleto", "Boleto"), ("pix", "Pix")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="producttransaction",
            name="succeeded",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
