# Generated by Django 4.2 on 2024-03-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0015_item_preview_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producttransaction",
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("complete_date"), descending=True, nulls_last=True
                    ),
                    "-complete_date",
                ],
                "verbose_name_plural": "transactions",
            },
        ),
        migrations.AddField(
            model_name="producttransaction",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("card", "Card"), ("boleto", "Boleto"), ("pix", "Pix")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="producttransaction",
            name="succeeded",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
