# Generated by Django 4.2 on 2024-03-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0016_producttransaction_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producttransaction",
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("complete_date"), descending=True, nulls_last=True
                    ),
                    "-complete_date",
                ],
                "verbose_name_plural": "transactions",
            },
        ),
    ]
