# Generated by Django 4.2 on 2024-03-28 16:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0017_alter_producttransaction_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstore",
            name="items_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), size=20
            ),
        ),
        migrations.AlterField(
            model_name="userstore",
            name="last_rotation_items_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), size=20
            ),
        ),
    ]
