#!/usr/bin/env bash

if [ $# -eq 0 ]
  then
    echo "É necessário informar o ambiente (prod ou staging) no primeiro argumento"
    exit 1
elif [[ ! "$1" =~ ^(staging|prod)$ ]];
  then
    echo "$1 precisa ser 'staging' ou 'prod'"
fi

ENVIRONMENT=$1

echo
echo "-> Iniciando deploy para $ENVIRONMENT......"
SERVER=reload-api-$ENVIRONMENT
USER=ubuntu

echo
echo "-> Enviando variáveis de ambiente..."
if [[ ! -f ".env.$ENVIRONMENT" ]] ; then
    echo "É necessário o arquivo '.env.$ENVIRONMENT' para continuar."
    exit
fi

echo
echo "-> Buildando e enviando versão do app..."
git archive -o /tmp/application.tar.gz HEAD
scp /tmp/application.tar.gz .env.$ENVIRONMENT $USER@$SERVER:/tmp/

DATE_NOW=$(date +"%Y%m%d_%H%M%S")

ssh $USER@$SERVER '
echo "-> Parando serviços..."
sudo systemctl stop nginx
sudo systemctl stop celery_beat
sudo systemctl stop celery_worker
sudo systemctl stop gunicorn
sudo systemctl stop uvicorn

echo
echo "-> Preparando backup..."
mv ~/application ~/bkp-'$DATE_NOW'

echo
echo "-> Descompactando nova versão da aplicação..."
mkdir ~/application
cd ~/application
tar zxvf /tmp/application.tar.gz
rm /tmp/application.tar.gz

echo
echo "-> Transferindo mídias..."
test -e ~/bkp-'$DATE_NOW'/media/ && \
        cp -R -p ~/bkp-'$DATE_NOW'/media/ ~/application/media

echo
echo "-> Comprimindo backup..."
zip -r ~/bkp-'$DATE_NOW'.zip ~/bkp-'$DATE_NOW'
rm -Rf ~/bkp-'$DATE_NOW'

echo
echo "-> Replicando envvars..."
> ~/.bash_profile
echo "" > ~/application/.env
while IFS== read -r key value
do
  if [[ $key =~ ^#.* ]] || [[ -z $value ]]; then continue; fi

  value="${value%\"}"
  value="${value#\"}"
  value="\"$value\""

  echo "$key=$value" >> ~/application/.env
  echo "export $key=$value" >> ~/.bash_profile
done </tmp/.env.'$ENVIRONMENT'
sed -i '/^$/d' ~/application/.env
echo "export PATH=$PATH:~/.local/bin/" >> ~/.bash_profile
source ~/.bash_profile
rm /tmp/.env.'$ENVIRONMENT'

echo
echo "-> Instalando dependências..."
cd ~/application
pipenv install

echo
echo "-> Rodando migrations..."
pipenv run migrate

echo
echo "-> Coletando arquivos estáticos..."
pipenv run collectstatic --no-input

echo
echo "-> Atualizando permissões..."
cd ~/
sudo chown -R ubuntu:www-data ~/application

echo
echo "-> Reiniciando serviços..."
sudo systemctl start gunicorn && \
sudo systemctl start uvicorn && \
sudo systemctl start celery_beat && \
sudo systemctl start celery_worker && \
sudo systemctl start nginx
'
