version: "3.9"

services:
  db:
    image: postgres
    command: postgres -c 'max_connections=6500'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Sao_Paulo

  redis:
    image: redis
    environment:
      - TZ=America/Sao_Paulo

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80

  django:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - db
      - redis
      - nginx
    command: uvicorn --host 0.0.0.0 --port 8000 --reload --workers 5 core.asgi:application
    restart: unless-stopped

  celery:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: celery -A core.celery.app worker -B -l info -c 5
    restart: unless-stopped

  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/locust_tests
    command: -f /locust_tests/locustfile.py --host=http://nginx:80
    depends_on:
      - nginx

volumes:
  db:
    name: reload_db
