version: "3.9"

services:
  db:
    image: postgres
    command: postgres -c 'max_connections=6500'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Sao_Paulo

  redis:
    image: redis
    environment:
      - TZ=America/Sao_Paulo

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80

  django:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - db
      - redis
      - nginx
    command: pipenv run start
    restart: unless-stopped

  celery:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: pipenv run celery_worker
    restart: unless-stopped

  locust:
    build: .
    env_file:
      - .env
    ports:
      - 8089:8089
    depends_on:
      - django
      - celery
    command: pipenv run locust
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  db:
    name: reload_db
