# Generated by Django 4.2 on 2023-07-02 04:41

from django.db import migrations


def create_default_settings(apps, schema_editor):
    AppSettings = apps.get_model("appsettings", "AppSettings")
    AppSettings.objects.create(
        kind='boolean',
        name='Maintenance Window',
        value='0',
    )
    AppSettings.objects.create(
        kind='integer',
        name='Matches Limit',
        value='20',
    )
    AppSettings.objects.create(
        kind='integer',
        name='Matches Limit Gap',
        value='5',
    )
    AppSettings.objects.create(
        kind='integer',
        name='Invite Required',
        value='0',
    )


class Migration(migrations.Migration):
    dependencies = [
        ("appsettings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_settings),
    ]
