# Generated by Django 4.1.4 on 2022-12-12 23:46

from django.db import migrations


def create_settings_invite_required(apps, _):
    AppSettings = apps.get_model('appsettings.AppSettings')
    AppSettings.objects.create(name='Invite Required', value='1', description='')


def delete_settings_invite_required(apps, _):
    AppSettings = apps.get_model('appsettings.AppSettings')
    AppSettings.objects.filter(name='Invite Required').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('appsettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_settings_invite_required, delete_settings_invite_required
        )
    ]
