# Generated by Django 4.2a1 on 2023-01-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsettings", "0002_auto_20221212_2046"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("integer", "Integer"),
                    ("boolean", "Boolean"),
                ],
                default="text",
            ),
        ),
    ]
