# Generated by Django 4.2 on 2023-10-24 15:02

from django.db import migrations


def create_default_settings(apps, schema_editor):
    AppSettings = apps.get_model("appsettings", "AppSettings")
    AppSettings.objects.create(
        kind='boolean',
        name='Beta Required',
        value='0',
    )


class Migration(migrations.Migration):
    dependencies = [
        ("appsettings", "0002_auto_20230702_0141"),
    ]

    operations = [
        migrations.RunPython(create_default_settings),
    ]
