# Generated by Django 4.2a1 on 2023-01-25 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appsettings", "0003_appsettings_is_active_appsettings_kind"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appsettings",
            options={
                "verbose_name": "App Settings",
                "verbose_name_plural": "App Settings",
            },
        ),
    ]
