# Generated by Django 4.2 on 2023-10-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsettings", "0003_auto_20231024_1202"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="appsettings",
            index=models.Index(fields=["name"], name="appsettings_name_02e0e5_idx"),
        ),
    ]
