# Generated by Django 4.2 on 2023-11-21 20:46

from django.db import migrations


def create_default_settings(apps, schema_editor):
    AppSettings = apps.get_model("appsettings", "AppSettings")
    AppSettings.objects.create(
        kind='boolean',
        name='Alpha Required',
        value='0',
    )


class Migration(migrations.Migration):
    dependencies = [
        ("appsettings", "0004_appsettings_appsettings_name_02e0e5_idx"),
    ]

    operations = [
        migrations.RunPython(create_default_settings),
    ]
