# Generated by Django 4.2 on 2023-07-14 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.TextField(
                        choices=[
                            (0, "Hate Speech"),
                            (1, "Chat Abuse"),
                            (2, "Report Abuse"),
                            (3, "Bad Conduct"),
                            (4, "Anti Game"),
                            (5, "Account Sharing"),
                            (6, "Cheating"),
                        ]
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("report_points", models.IntegerField(default=0)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="reportanalysis",
            name="account",
        ),
        migrations.RemoveField(
            model_name="reportanalysis",
            name="analyst",
        ),
        migrations.RemoveField(
            model_name="account",
            name="report_points",
        ),
        migrations.DeleteModel(
            name="Report",
        ),
        migrations.DeleteModel(
            name="ReportAnalysis",
        ),
        migrations.AddField(
            model_name="accountreport",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.account"
            ),
        ),
    ]
