# Generated by Django 4.2a1 on 2023-02-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_email_update",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="latest email update date"
            ),
        ),
    ]
