# Generated by Django 4.2 on 2023-07-14 22:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_accountreport_remove_reportanalysis_account_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountreport",
            old_name="create_date",
            new_name="datetime_created",
        ),
    ]
