# Generated by Django 4.2rc1 on 2023-03-28 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_date_inactivation"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="report_points",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ReportAnalysis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                (
                    "restriction_time",
                    models.IntegerField(help_text="In hours.", null=True),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_set",
                        to="accounts.account",
                    ),
                ),
                (
                    "analyst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.TextField(
                        choices=[
                            (0, "Hate Speech"),
                            (1, "Chat Abuse"),
                            (2, "Report Abuse"),
                            (3, "Bad Conduct"),
                            (4, "Anti Game"),
                            (5, "Account Sharing"),
                            (6, "Cheating"),
                        ]
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_set",
                        to="accounts.account",
                    ),
                ),
            ],
        ),
    ]
