# Generated by Django 4.2 on 2023-07-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_create_date_accountreport_datetime_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountreport",
            name="subject",
            field=models.IntegerField(
                choices=[
                    (0, "Hate Speech"),
                    (1, "Chat Abuse"),
                    (2, "Report Abuse"),
                    (3, "Bad Conduct"),
                    (4, "Anti Game"),
                    (5, "Account Sharing"),
                    (6, "Cheating"),
                ]
            ),
        ),
    ]
