# Generated by Django 4.2 on 2023-05-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_account_report_points_reportanalysis_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="highest_level",
            field=models.IntegerField(default=0),
        ),
    ]
