# Generated by Django 4.2 on 2023-07-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_user_accounts_us_email_74c8d6_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_staff"], name="accounts_us_is_staf_337a26_idx"
            ),
        ),
    ]
