# Generated by Django 4.2 on 2023-08-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_user_accounts_us_is_staf_337a26_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="social_handles",
            field=models.JSONField(
                default={"discord": None, "twitch": None, "youtube": None}
            ),
        ),
    ]
