# Generated by Django 4.2 on 2023-08-09 18:40

import accounts.models.account
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_account_social_handles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="social_handles",
            field=models.JSONField(
                default=accounts.models.account.get_default_social_handles
            ),
        ),
    ]
