# Generated by Django 4.2 on 2023-11-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_user_status_user_accounts_us_status_6bbe13_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountreport",
            name="report_points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
