# Generated by Django 4.2 on 2023-11-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_alter_accountreport_report_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="coins",
            field=models.IntegerField(default=0),
        ),
    ]
