# Generated by Django 4.2 on 2023-11-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_account_coins"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_alpha",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_beta",
            field=models.BooleanField(default=False),
        ),
    ]
