# Generated by Django 4.2 on 2024-01-05 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_user_is_alpha_user_is_beta"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reason_inactivated",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user requested", "User Requested"),
                    ("user ban", "User Ban"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="BannedUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("cheating", "Cheating"),
                            ("repeated missconduct", "Repeated Missconduct"),
                            ("multiple account banned", "Multiple Account Banned"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "agent",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ban",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Banned User",
                "verbose_name_plural": "Banned Users",
            },
        ),
    ]
