# Generated by Django 4.2 on 2024-01-09 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_user_reason_inactivated_banneduser"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_end", models.DateField()),
                ("is_revoked", models.BooleanField(default=False)),
                (
                    "revoke_subject",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("last chance", "Last Chance"),
                            ("wrong", "Wrong"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("cheating", "Cheating"),
                            ("repeated missconduct", "Repeated Missconduct"),
                            ("multiple account banned", "Multiple Account Banned"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Links to images, videos or a detailed explanation thatcould help others to understand why the ban was applied or revoked."
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userbans_applied",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoke_agent",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userbans_revoked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ban",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Ban",
                "verbose_name_plural": "Users Bans",
            },
        ),
        migrations.DeleteModel(
            name="BannedUser",
        ),
    ]
