# Generated by Django 4.2 on 2024-03-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_userban_delete_banneduser"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["level"], name="accounts_ac_level_b8b1d4_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["level_points"], name="accounts_ac_level_p_05e907_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_superuser"], name="accounts_us_is_supe_edd34d_idx"
            ),
        ),
    ]
