# Generated by Django 4.2 on 2024-03-19 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "allowed_to",
                    models.CharField(
                        choices=[
                            ("alpha", "Alpha"),
                            ("beta", "Beta"),
                            ("early", "Early"),
                            ("active", "Active"),
                            ("online", "Online"),
                            ("verified", "Verified"),
                            ("selected", "Selected"),
                            ("none", "None"),
                            ("all", "All"),
                        ],
                        default="none",
                        help_text='If "selected" option is selected, you must choose, at least, one user to allow this feat. If any other option is selected, "selected users" will be ignored and erased',
                        max_length=16,
                    ),
                ),
                (
                    "selected_users",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
