# Generated by Django 4.2 on 2024-03-19 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="restricted_to",
            field=models.CharField(
                choices=[
                    ("alpha", "Alpha"),
                    ("beta", "Beta"),
                    ("early", "Early"),
                    ("active", "Active"),
                    ("online", "Online"),
                    ("verified", "Verified"),
                    ("selected", "Selected"),
                    ("all", "All"),
                ],
                default="all",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="selected_users",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
