# Generated by Django 4.2 on 2024-03-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("features", "0002_feature_restricted_to_feature_selected_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="restricted_to",
        ),
        migrations.AddField(
            model_name="feature",
            name="allowed_to",
            field=models.CharField(
                choices=[
                    ("alpha", "Alpha"),
                    ("beta", "Beta"),
                    ("early", "Early"),
                    ("active", "Active"),
                    ("online", "Online"),
                    ("verified", "Verified"),
                    ("selected", "Selected"),
                    ("none", "None"),
                    ("all", "All"),
                ],
                default="none",
                max_length=16,
            ),
        ),
    ]
