apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: default
  labels:
    app: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      containers:
        - name: api
          image: us-central1-docker.pkg.dev/alpine-comfort-381901/reload-api/api:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: api-staging-env
          ports:
            - containerPort: 80

      imagePullSecrets:
        - name: do-container-registry
