apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      containers:
        - name: api
          image: registry.digitalocean.com/gta-mm-k8s/api:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: api-staging-env
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: gta-mm-k8s
