apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reoad-api-ingress
  annotations:
    networking.gke.io/managed-certificates: "reload-api"
spec:
  rules:
    - host: api.dev.reloadclub.gg
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: api-service
                port:
                  number: 80
