apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api-deployment
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
