apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: default
  labels:
    app: api-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: api-deployment
