# Generated by Django 4.2 on 2023-04-20 15:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "to_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("online_users", models.BooleanField(default=False)),
                ("active_users", models.BooleanField(default=False)),
                ("content", models.TextField()),
                ("create_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
