# Generated by Django 4.2 on 2023-04-20 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemnotification",
            name="to_ids",
        ),
        migrations.AddField(
            model_name="systemnotification",
            name="to_users",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
