# Generated by Django 4.2 on 2023-04-21 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0003_remove_systemnotification_active_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemnotification",
            name="to_users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
