name: Build and Deploy to GKE

on:
  workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows: ["Lint & Test"]
    types:
      - completed
  push:
    branches: [staging]

env:
  PROJECT_ID: alpine-comfort-381901
  GAR_LOCATION: us-central1
  REPOSITORY: reload-api
  IMAGE: api

jobs:
  setup-build-publish-deploy:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to GAR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_CREDENTIALS }}

    - name: Build
      run: |-
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    - name: Publish
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest"
